server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ssm
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
mybatis:
  mapper-locations: com/wjm/postgers/dao/*.xml
  type-aliases-package: com/wjm/postgers/domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=conutSql
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  identity: PostgerSQL