server:
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisNoSQLMM
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ssm
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8

logging:
  level:
    root: debug
    com.wjm: debug